/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_theemuts_remotedesktop_transform_IDCT */

#ifndef _Included_com_theemuts_remotedesktop_transform_IDCT
#define _Included_com_theemuts_remotedesktop_transform_IDCT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_theemuts_remotedesktop_transform_IDCT
 * Method:    idct
 * Signature: ([I[I)V
 */
JNIEXPORT void JNICALL Java_com_theemuts_remotedesktop_transform_IDCT_idct
  (JNIEnv *, jclass, jshortArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
